### ISSUE TITLE
Assessment 2

### ISSUE THREAD

**Issue by rizzamandasari** [DianneDini/mobpro1_assessment2#1]
Aplikasi dapat berjalan dengan baik namun
1. Tujuan dari aplikasi tidak jelas. Tidak disebutkan peruntukannya untuk apa?
2. Fitur dari Assessment 1 ada yang hilang seperti Bahasa.
3. Tombol FAB mmenghalangi list.
Perbaikan dapat disubmit maksimal 25 Juni 2024

**Comment by DianneDini** [comment]
1. Aplikasi ini merupakan aplikasi pencatat kesehatan yang dapat digunakan oleh 
tenaga medis maupun digunakan oleh individu secara pribadi. Para tenaga medis 
dapat menggunakan aplikasi ini untuk melacak perkembangan kondisi pasien dari 
waktu ke waktu. Sementara itu, bagi user yang menggunakan aplikasi ini untuk 
kepentingan pribadi, aplikasi ini dapat digunakan untuk mencatat kondisi kesehatan
seperti gejala yang dirasakan sebelum dilaporkan ke tenaga medis, atau dapat juga 
digunakan ketika user ingin mencatat diagnosis yang diberikan oleh tenaga medis
agar dapat memantau perkembangan kesehatan diri sendiri dari rumah.
Di MainScreen juga ditambahkan keterangan dari tujuan aplikasinya ketika user belum memasukan data apapun atau ketika data masih kosong.

2. Fitur Bahasa sudah ditambahkan dan sudah dipush ke github.

3. Tombol FAB tidak menghalangi list maupun grid seperti yang terlihat pada 2 video screenrecord aplikasinya di bawah ini
(https://github.com/DianneDini/mobpro1_assessment2/assets/114900331/454b652e-ca33-49f4-b10d-6c7414d99f9b)

(https://github.com/DianneDini/mobpro1_assessment2/assets/114900331/c0e8923a-7de7-4fc3-b3a0-cde37a31c89f)
https://github.com/DianneDini/mobpro1_assessment2/assets/114900331/754d8dd7-9f72-41ac-aeae-3049408dcf03


https://github.com/DianneDini/mobpro1_assessment2/assets/114900331/070a4abf-e33c-4ef2-bfc7-5ee2f5ecc62b



Perbaikan dan video screenrecord untuk bukti nomor 3 sudah diupload ulang ke lms Mini Project #2

**Comment by DianneDini** [comment]
https://github.com/DianneDini/mobpro1_assessment2/assets/114900331/3a21d332-207c-4e81-899c-8572bd1166f8

Maaf disubmit ulang ibu, karena submit yang awal yang muncul hanya 1 video, 1 video lagi tidak muncul. 
Untuk video screenrecordnyanya saya masukan ke "Catatan lain-lain terkait project yang ingin disampaikan" dalam Rubrik Nilai Asesmen 2 yang diupload ulang di LMS

**Comment by rizzamandasari** [comment]
Ok. Close
